### ISSUE TITLE
Why do you stop maintaining mutsu?

### ISSUE THREAD

**Issue by veer66** [boutros/matsu#4]
This topic is not interesting anymore or there is another better solution? Do you mind suggesting?

**Comment by boutros** [comment]
I stopped because i found just having queries as text and intererpolating variables simpler and good enough. Dynamically created queries didn't turn up so often in my aplications anyway.

Also I hardly work with Clojure anymore. 

I'd be happy to turn over the repo to anyone willing to maintain/develop further.

**Comment by veer66** [comment]
Thank you.
